version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - basex

  basex:
    image: basex/basex:latest
    ports:
      - "8984:8984"
      - "1984:1984"
    volumes:
      - ./data:/opt/basex/data
