# Imagen oficial de BaseX con HTTP REST
FROM basex/basexhttp:latest

# Copiamos el directorio data/ dentro del contenedor
COPY data /opt/basex/data

# Exponemos los puertos de BaseX: 8984 (REST) y 1984 (GUI)
EXPOSE 8984 1984
